# Generated by Django 6.1.1 on 2026-09-20 00:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_public_id_ticketcomment_is_internal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcomment',
            name='tagged_agents',
            field=models.ManyToManyField(blank=True, related_name='tagged_in_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
